imports:
    - { resource: services_common.yaml }

services:
    # Make all services public for testing purposes
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'
            - '../src/Domain/DTO/'
        public: true
        autowire: true
        autoconfigure: true
